### PR TITLE
Fix exception in browser where module is undefined

### PR DESCRIPTION
**Pull request by vkurlyan**
Please, accept this fix because now library just broken in any browser

### CODE REVIEW

**Comment by ArnoudAdyen** [comment]
Yes. My apology for overlooking this. However, If I merge this, I feel we should also check for null explicitly. Agreed?

So if (typeof module !== "undefined" && module && module.exports)

**Comment by vkurlyan** [comment]
in the same file you can see same check for sjcl.js

> "undefined"!==typeof module&&module.exports

So, anyway this library will not work if someone defines 'module' as null.

**Comment by ArnoudAdyen** [comment]
You are correct. I will look into the `null` scenario later. For now make sure the library works in the most common cases. Thank you for creating the pull.

**Comment by vkurlyan** [comment]
Thanks for fast accepting

**Pull request merged**
