### PR TITLE
Improve validation for card expiration year

### PR DESCRIPTION
**Pull request by ivantsov**
More information here - https://github.com/Adyen/CSE-JS/issues/19

### CODE REVIEW

**Comment by ArnoudAdyen** [comment]
Hi,

Thank you very much for adding this change. I need to look into the topic further. Arguably the timezone in the browser might be different from the servers, flagging a card invalid in the last hours of the month in which it might actually still be valid. That is no argument to leaving the validation as wide as it is currently though. If we fully dive into the topic, we might consider a year to be only valid when it is ranging from [browser fullYear - 1 year, until browser fullYear + 10] years. (Assuming no card has an expiry year much more than 10 years from now). This assumption I need to validate internally however before applying the change.

Rgds,

Arnoud

**Comment by ivantsov** [comment]
Thanks for the response. Actually I think that validation of expiration date should consider not only year but month as well. For instance, _July 2016_ is a valid date right now but _June 2016_ isn't.

So, this PR is just a minor fix, but it doesn't fix the whole validation problem.

**Comment by ArnoudAdyen** [comment]
For the next version of the library we will be adding a [-2 years, + 15 years] year range restriction. In the end it is up to the issuer to accept expired cards and we need to send also those cards up for authorization. The issuer might have special exceptions for some cards even though they are expired.

For the CSE library cards older than two years are edge cases and a stricter validation to counter some of the invalid years caused by shoppers mistyping adds value to the library.

**Comment by ivantsov** [comment]
Glad to hear it. 
Also I think it would be great to add ability to create/override validation, because as you said the issuer might have special exceptions. And it's really hard now to modify a validation behavior for fields which validated by adyen library.

**Pull request closed without merging**
